# services:  
  nginx:
    image: nginx:stable-alpine
    container_name: nginxThree
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - VolumeThree:/Volum:rw
      - ./things/nginx/www/index.html:/Volum/nginx/www/index.html
      - ./things/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  server:
    image: centos:latest
    container_name: centosThree
    volumes:
      - VolumeThree:/Volum:rw
      - ./things/nginx/script:/Volum/nginx/www/scr/script
    command: [/Volum/nginx/www/scr/script]
  
  certbot:
    image: certbot/certbot:latest
    container_name: certbotThree
    volumes:
      - VolumeThree:/Volum:rw
      - ./things/nginx/www:/Volum/nginx/www
      - ./things/certbot:/etc/letsencrypt
    command: [cp /var/log/letsencrypt/letsencrypt.log /Volum/letsencrypt.log]
